### PR TITLE
[OFE-109]- Ensure we maintain our ANBI status in 2021

### PR DESCRIPTION
**Pull request by nashthecoder**
[OFE-109]- Ensure we maintain our ANBI status in 2021

 - added anbi-status file as collections, 
 - changed config.yml to include anbi as collections, 
 - created link button on resources.html for anbi-status 
 - added css for the anbi-link in the _block.scss file

Video:  https://user-images.githubusercontent.com/15178823/131813770-358fd25a-3e46-4966-b559-5225f8799ed4.mov

[OFE-109]: https://triggerise.atlassian.net/browse/OFE-109

### CODE REVIEW

**Review by a-bresler — APPROVED** [review]
Looks good! 

giphy

Do we only get the 2021 doc at the end of 2021?

**Comment by tiagovarela** [comment]
@nashthecoder The video shows that this interaction is a bit inconsistent with what is expected on the page. 

The link to ANBI is on something that resembles a filter, but when we click it a new page opens (instead of the expected filtering of results for ANBI).

(will we have more than 1 document for ANBI per year like we have for the other reports? Could we place it as one of the rectangles for a report (of a different type) and filter when we click on the link? Or place the link outside of the filters section?)

**Comment by nashthecoder** [comment]
@tiagovarela Got you, I will rework it.

**Comment by nashthecoder** [comment]
@tiagovarela I have implemented the filter and the selections are working as they should. I am having a challenge with keeping the ANBI doc only on All selection and ANBI selection.
How would I hide it when the user click Annual and Finance tabs - would it be best to implement in liquid on the resources html page or in the main.js. 

All Tab
Annual Tab
Finance Tab
ANBI Tab

**Comment by nashthecoder** [comment]
@tiagovarela Thank you very much for your support to get this work! 

[OFE-109]Anbi Status Added.mov

https://user-images.githubusercontent.com/15178823/133234320-29c6fdeb-8934-4e85-a69e-8aa25471d3c9.mov



[OFE-109]: https://triggerise.atlassian.net/browse/OFE-109

**Review by richmungla — APPROVED** [review]
LGTM

**Pull request merged**
