### PR TITLE
[MVC-1181]Removed ecosystem section from the website

### PR DESCRIPTION
**Pull request by nashthecoder**
[MVC-1181]Removed ecosystem section from the website. 
 - While trying to preview on Siteleaf  - there was an error 
` Liquid Exception: Could not locate the included file 'ecosystem.html' in any of ["/_includes", "/hoosegow/.bundle/ruby/2.6.0/gems/jekyll-theme-primer-0.5.4/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /_layouts/home.html (RuntimeError) `. 
Fixed the issue locally. 

[MVC-1181]: https://triggerise.atlassian.net/browse/MVC-1181

### CODE REVIEW

**Review by coertg — APPROVED** [review]

**Review by raguiar9080 — COMMENTED** [review]
I thought most of things were already removed via what was merged here: https://github.com/Triggerise/triggerise.github.io/pull/33/files

Shouldn't this only be the 3 line change on the home layout? Looking at develop it seems it was indeed merged. I feel like I'm missing something.

**Comment by nashthecoder** [comment]
Screenshot 2021-05-27 at 18 17 58
Screenshot 2021-05-27 at 18 18 07
@raguiar9080 it was refusing to review so I had to go back and check... 
this is what I changed : https://github.com/Triggerise/triggerise.github.io/pull/35/commits/a3ddde229ee873f0e60f3aa05618965cee6ca471

**Comment by tiagovarela** [comment]
@nashthecoder @raguiar9080 yes this PR should contain only commit https://github.com/Triggerise/triggerise.github.io/commit/a3ddde229ee873f0e60f3aa05618965cee6ca471

The other commit is already in the develop branch. This PR diff shows more because of the squash merge maybe?

**Comment by nashthecoder** [comment]
> @nashthecoder @raguiar9080 yes this PR should contain only commit [a3ddde2](https://github.com/Triggerise/triggerise.github.io/commit/a3ddde229ee873f0e60f3aa05618965cee6ca471)
> 
> The other commit is already in the develop branch. This PR diff shows more because of the squash merge maybe?

So what the best step forward?

**Comment by tiagovarela** [comment]
@nashthecoder Squash and merge this PR as is should be ok. (even though it says it will delete files that were already deleted in develop)

For future PRs: create a new branch from the latest develop to work on the fix since reusing the existing branch will contain commits that have changes that were applied already.

**Pull request merged**
