### PR TITLE
"Our model" section on the home page fixes. Site dependancies upgraded

### PR DESCRIPTION
**Pull request by andregdias**

### CODE REVIEW

**Comment by andregdias** [comment]
This white "bar"/space is now showing in the main page, below the top bar.

image

Production:
image

**Comment by SydneyMhashu** [comment]
I must have missed that when i was testing. Let me look into it

**Comment by andregdias** [comment]
As you probably noticed, I've also added the `.gitignore` file as GitHub Pages generates the `_site` folder while compiling and ignores the one on the repo.
This makes it a lot cleaner and easier to read the PR.

**Comment by SydneyMhashu** [comment]
Yes thats great since GitHub Pages will rebuild site anytime a commit is pushed

**Pull request merged**
